version: "3.4"

volumes:
  openstates-postgres:
    name: openstates-postgres

services:
  scrape:
    image: openstates/openstates
    environment:
    - MYSQL_HOST=mysql
    - DATABASE_URL=postgres://openstates:openstates@postgres:5432/openstatesorg
    - NEW_YORK_API_KEY
    - INDIANA_API_KEY
    - USER_AGENT
    - PUPA_ARGS
    volumes:
    - .:/opt/openstates/openstates/
    entrypoint: /opt/openstates/openstates/pupa-scrape.sh
  postgres:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_PASSWORD: openstates
      POSTGRES_USER: openstates
      POSTGRES_DB: openstatesorg
    volumes:
    - openstates-postgres:/var/lib/postgresql/data
  mysql:
    image: mariadb:10.3
    command: mysqld_safe --max_allowed_packet=512M
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=capublic
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  ca-download:
    image: openstates/openstates
    entrypoint: /opt/openstates/openstates/openstates/ca/download.sh
    environment:
    - MYSQL_HOST=mysql
    volumes:
    - .:/opt/openstates/openstates/
    depends_on:
    - mysql
